#
#   GENERAL SETTINGS
#

debug: false

# The minetail's config file
DataSource:
  # What type of database do you want to use?
  # Available values: SQLITE, MYSQL.
  backend: MYSQL
  # Database host address
  mySQLHost: localhost
  # Database port
  mySQLPort: '3306'
  # Username to connect to the MySQL database
  mySQLUsername: 'minecraft'
  # Password to connect to the MySQL database
  mySQLPassword: 'E7BnEjOEcM7F'
  # Database Name
  mySQLDatabase: 's15_fairy'

#
#   AUTH SERVER SETTINGS
#

# Fairy Tail server settings
host: "localhost"
port: 25562
maintenance: false
maintenancebypass:
  - "Minat0_"

# Default settings for Mage when player register
magicLevel: 1

#
#   FAIRYTALE SERVER SETTINGS
#

# BossBar on spell disappear time (in seconds)
# Set it on 0 or -1 to disable disappear
disappearTime: 3
bossBarDefaultColor: PINK

Conversations:
  ChangeClass:
    - "Внимание!"
    - "Вы действительно хотите сменить свой класс?"
    - "Сбросив класс на 20 уровне, вы повышаете шанс выбить более лучший набор."
    - "Требования:"
    - "- 10 уровень"
    - "- 2500000 драгоценностей"
    - "Введите в чат: Да / Нет"

# GUIs (works only on Auth server)
GUI:
  register:
    title: "Регистрация | Выбор класса"
    format:
      - "   s k   "
    items:
      HOLDING_MAGIC:
        material: DIAMOND_SWORD
        key: s
        lore:
          - Держательная Магия
          - '--------------------'
          - Этот тип магии требует,
          - чтобы Волшебник использовал
          - внешний источник для создания Волшебной силы.
      CASTER_MAGIC:
        material: DIAMOND_AXE
        key: k
        lore:
          - Магия Заклинателя
          - '--------------------'
          - Этот тип магии требует,
          - чтобы Волшебник использовал
          - внешний источник для создания Волшебной силы.

Kits:
  CASTER_MAGIC:
    LEGENDARY:
      Natsu:
        - fireball
        - Firewalk
        - combust
        - fireleap
    MYTHICAL:
      Meri:
        - Virus
    RESTRICTED:
      KlaivGilders:
        - pasivegildart
        - TheFirmament
    MILITARY:
      BakysGroh:
        - Pasivestrong
    INDUSTRIAL:
      AranaVebb:
        - ThreadShot
      Berrik:
        - lightings
  HOLDING_MAGIC:
    LEGENDARY:
      Dget:
        - falconstricke
        - Highspeed
        - pasivedget
    MYTHICAL:
      Polyshka:
        - Heal
    RESTRICTED:
      Obra:
        - UndMagic
    MILITARY:
      Hibiki:
        - PowerExplosion
        - walls
    INDUSTRIAL:
      MestGraider:
        - StraightLine
      Cheiz:
        - Shadow