name: MineTail
author: Minat0_
version: ${project.version}
api-version: 1.16
main: ru.minat0.minetail.MineTail
softdepend:
  - "AuthMe"
  - "MagicSpells"
  - "CMI"
  - "MythicMobs"
  - "PlaceholderAPI"
commands:
  minetail:
    description: Список главных комманд сервера.
    aliases:
      - mt
permissions:
  minetail.player.register:
    description: Регистрация на сервере. Производится один раз при заходе на сервер.
  minetail.admin.config:
    description: Перезагрузить конфигурацию плагина.
  minetail.admin.change.class:
    description: Сменить магический класс игроку.

